- scour/scour.py
This PR adds three new options:
* `--nindent` which allows to set the indentation depth (e.g. 2 spaces) therefore giving the user the possibility to adjust the pretty-printing to his personal preferences.
* `--no-line-breaks` which suppresses line breaks (and obviously also indentation) in the output altogether. This closes #10 and adds a possibility for a "minimal" output.
* `--strip-xml-space` tells Scour to remove the `xml:space` attribute from the root SVG element. At least one popular vector graphics editor adds `xml:space="preserve"` to the root SVG element thereby thwarting our efforts to pretty-print the output completely.
> Add some options to optimize pretty-printing

- scour/scour.py
This is a small compatibility fix that should make the current version of Scour fully compatible with Python 2.6.5 again.
> Compatibility fix for Python 2.6

- scour/scour.py
* The separate treatment of comments at the documentElement's level is not necessary - they have a parent (as tested in Python 3.5.0 and 2.7.11 and 2.6.6)! It might not have worked before due to a typo - note the "if isinstance(element,...)" and "len(element.data)" which should both refer to "subelement" instead - or a bug in very old versions of Python).
* Fix the iteration over childNodes (i.e. replace "for subelement in element.childNodes:" with ""for subelement in element.childNodes[:]:". We have to create a copy of the list to iterate over, otherwise we'd be iterating over a list as we change it which leads to unpredictable results.
Fixes #25
> Simplify and fix "removeComments()"

- scour/scour.py
- testscour.py
This PR adds an easy way to sanitize an `options` object that should be passed to `scourString`/`scourXmlFile`.
By generating a set of default options and "merging in" know attributes from the options passed to the function it is ensured that all attributes are correctly set (default values are used for unspecified attributes) while also removing unknown attributes.
Firstly this makes it easier to use Scour from another script (Instead of requiring explicit calling of `generateDefaultOptions` to get a copy of the latest options which have to be modified and fed back into Scour it's enough to generate an object that contains just the attributes that one wants to change).
Secondly it will avoid compatibility issues that may arise in case any options are added/removed/renamed in the future.
> Mechanism for sanitizing options

- scour/scour.py
This is just a small cosmetic in the console output.
Since it already looks like a fraction, I guess we should order new/old size accordingly so it actually represents the displayed quotient of file sizes.
> Switch order of new/old size in console output

- scour/scour.py
- Allow the common way to specify input/output files as positional arguments, e.g.<br>`scour input.svg output.svg`.
- Make `--help` output much clearer by using option groups:
```
scour 0.33
Copyright Jeff Schiller, Louis Simard, 2010
Usage: scour.py [INPUT.SVG [OUTPUT.SVG]] [OPTIONS]
If the input/output files are not specified, stdin/stdout are used. If the
input/output files are specified with a svgz extension, then compressed SVG is
assumed.
Options:
--version                      show program's version number and exit
-h, --help                     show this help message and exit
-q, --quiet                    suppress non-error output
-v, --verbose                  verbose output (optimization statistics,
etc.)
-i INPUT.SVG                   alternative way to specify input filename …
```
> Facilitate command line usage

- Makefile
- scour/scour.py
- testscour.py
- unittests/flowtext-less.svg
- unittests/flowtext.svg
This fixes https://github.com/codedread/scour/issues/49 in a pragmatic way
> add option to check and warn or bail out on flowtext

- scour/scour.py
If a tag has many attributes it can be hard to visually find the attribute you are looking for. Especially since many similar tags might have a very different order of the same attributes.
Therefore this patch adds a new option `--order-attributes` which orders the attribute alphabetically. It still keeps the `id` attributes in the front (as it was already before).
> add --order-attributes option

- scour/scour.py
- testscour.py
- In text nodes quotes are fine
- In attributes quotes are fine if used reciprocally.
Escaping in the latter case often causes issues, e.g. with quoted font names (#21) or inline CSS styles (#56), while it probably does not gain anything (if quotes are wrongly used in attribute names the XML is most likely invalid to start with)
> Don't escape quotes ('/") in text nodes and attributes.

- scour/scour.py
- testscour.py
> Print usage information if no input file was specified (and no data is available from `stdin`)

- scour/scour.py
> Redirect informational output to `stderr` when SVG is output to `stdout`

- scour/scour.py
This module does not work with Python 2.7 and later, according to https://pypi.python.org/pypi/psyco/1.6 and http://psyco.sourceforge.net.
> Remove obsolete Psyco dependency

- scour/scour.py
- testscour.py
- unittests/descriptive-elements-with-text.svg
- unittests/empty-descriptive-elements.svg
- unittests/full-descriptive-elements.svg
Closes #38. I’ve added three new options:
- `--remove-titles` (removes `<title>`)
- `--remove-descriptions` (removes `<desc>`)
- `--remove-descriptive-elements` (removes `<title>`, `<desc>` and `<metadata>`)
I’ve also added tests for each (9 in total) and modified the corresponding SVG files. I’m not that familiar with Python, so constructive comments are appreciated! I wasn’t sure about adding a type check to `removeDescriptiveElements()` (for the set type), but apparently that is not very Python’y?
> Add options to remove descriptive elements

- scour/scour.py
Addresses part of #60.
The order within the `style` value should imo be handled separately.
> always order attributes based on defined order of known attributes, otherwise alphabetical

- scour/scour.py
- testscour.py
- unittests/collapse-same-path-points.svg
- unittests/path-no-optimize.svg
Paths are now optimized while using the full numerical precision. The number of digits is reduced at the very end of the process.
This significantly increases accuracy for some problematic samples like #80.
> Improve path scouring

- scour/scour.py
- testscour.py
- unittests/duplicate-gradients-update-style.svg
- unittests/remove-duplicate-gradients.svg
Fix replacement of duplicate gradients if "fill/stroke" contains fallbacks.
(fixes #79)
> Duplicate gradients with fallback

- scour/scour.py
Add a seperate precision option for curve control points
(--set-c-precision) . Interpret precision digits = 0 as round to nearest
integer between -1 and 1. Add option to preserves all digits left of
decimal point regardless of set precision.
> Improve precision options for smaller output size

- scour/scour.py
The code used to look like this:
if child.nodeType == 1:
...
Now, the code looks like this:
if child.nodeType == Node.ELEMENT_NODE:
...
> scour.py: Use named constants rather than literal integers for `nodeType'

- scour/scour.py
The attributes `id` and `xml:id` have been handled specially, though there has been little advantage in doing so. After merging this pull request, the same code will be used to handle every attribute.
> Consolidate the code for serializing attributes

- scour/scour.py
- testscour.py
- unittests/entities.svg
- unittests/quotes-in-styles.svg
The following commit removed the escaping of single quotes and double quotes, in order to fix issues #21 and #56:
&nbsp;&nbsp;&nbsp;&nbsp;**commit** 57f93efc894b1ba4c30e42b549b0081185029c36  
&nbsp;&nbsp;&nbsp;&nbsp;**Date:** Tue Aug 16 00:10:41 2016 +0200
However, this broke the quoting of an attribute value that has both a single quote and a double quote (see below for an example). This patch series re-introduces the escaping of quotes, but ultimately uses entities only when both a single quote and a double quote are present at the same time in an attribute value; whether single quotes or double quotes are escaped depends on which choice produces the shortest result. Unit tests are included.
-------------
The following presents a concrete, real-world example of the problem that is being …
> Fix regression with regard to quotes in attribute values

- scour/scour.py
The biggest win (at least in my test case) is the "findReferencedElements: Handle referencingProps separately", which avoids a large number of unnecessary string operations.
But there is also a large potential in "Avoid recomputing findReferencedElements in removeUnusedDefs" for any SVG that need a number of calls to "removeUnreferencedElements" or where "removeUnusedDefs" recurses a lot of times.  My particular test case does not seem to trigger any of that though (with a total of one call to removeUnreferencedElements)
> Optimize find referenced elements

- scour/scour.py
The automated python2 -> python3 converter creates some suboptimal
code patterns in some cases, notably in its handling of dicts.
This commit handles the following cases:
* "if x in list(y.keys()):" => "if x in y:"
The original code is neuters the O(1) lookup effeciency of a dict
by turning it into a list.  This occurs a O(n) in converting it to
a list and then another O(n) for the lookup.  When done in a loop,
this becomes O(n * m) rather than the optimal O(m).
* "for x in list(y.keys()):" => "for x in y:" OR "for x in list(y):"
A dict (y in these cases) operates as an iterator over keys in the
dict by default.  This makes the entire "list(y.keys())" dance
redundant _in most cases_.  In a some cases, scour modifies the
dict while iterating over it and in those cases, we need a
"list(y)" …
> Rewrite redundant codepatterns introduced by py2 -> py3 conversion

- scour/scour.py
The unprotected_ids function returns all unprotected ids and
removeUnreferencedIDs removes all of them that does not appear in the
return value of findReferencedElements.
On closer observation it turns out that removeUnreferencedIDs cannot
cause nodes/IDs to become unprotected nor unreferenced (as it only
remove the "id" attribute, not the node).  With this in mind, we can
just remove the loop and save a call to all of these functions.
> Remove an unnecessary loop

- scour/scour.py
The original implementation of removeDuplicateGradient does O(n²)
search over all gradients to remove duplicates.  In images with many
gradients (such as [MediaWiki_logo_1.svg]), this becomes a significant
overhead as that logo has over 900 duplicated gradients.
We solve this by creating a key for each gradient based on the
attributes we use for duplication detection.  This key is generated
such that if two gradients have the same key, they are duplicates (for
our purpose) and the keys are different then the gradients are
guaranteed to be different as well.  With such a key, we can rely on a
dict to handle the duplication detection (which it does very well).
This change improves the runtime performance on [MediaWiki_logo_1.svg]
by about 25% (8m51s -> 1m56s on 5 runs).
Original:
$ time for …
> Avoid O(n²) in removeDuplicateGradient

- scour/scour.py
As of python3.3, the recommended method for obtaining a performance
timer is no longer "time.clock()" but "time.perf_counter()".  By using
time.perf_counter, we outsource the problem for finding the best
performance messaurement to python.  Plus, we also avoid inaccurate
timings if the system time is changed during the processing of the SVG
image on platforms where we used to use "time.time()".
For python2 and python3 before 3.3, we still have to use the original
timers.
> Use time.perf_counter when available

- scour/scour.py
- scour/svg_regex.py
- testscour.py
- unittests/path-elliptical-flags.svg
- properly parse paths without space after boolean flags (fixes #161)
- omit space after boolean flag to shave off a few bytes when not using renderer workarounds
> Fix handling of boolean flags in elliptical path commands

- scour/scour.py
This reduces runtime by ~15-25% on the 1_42_polytope_7-cube.svg case provided in #184 (tested with python3).  Note that the runtime is still 5-6 minutes after this, so I would not consider #184 closed with just this commit.
> Gh 184 perf faster remove default attr value

- scour/scour.py
- testscour.py
- unittests/transform-scale-is-identity.svg
The scale function on the transform attribute has a short form, where
only the first argument is used.  But optimizeTransform would always
assume that there were two when checking for the identity scale.
Closes: #190
> Avoid crashing on "scale(1)" (short for "scale(1, 1)")

- scour/scour.py
- testscour.py
- unittests/path-command-rewrites.svg
- unittests/path-empty-move.svg
As observed in #163, scour sometimes do some unsafe path rewrites.
This branch solves that issue by separating the logic for removing path segments from the logic for rewriting commands.  The first commit removes the current unsafe optimization and the next one reimplements it (and adds a few more test cases for path cleaning of commands).
> Correct handling of "m0 0" vs. "z" commands

- scour/scour.py
- testscour.py
- unittests/remove-default-attr-order.svg
- unittests/remove-default-attr-std-deviation.svg
Scour tried to handle "order" attribute as a SVGLength.  However, the
"order" attribute *can* consist of two integers according to the
[SVG 1.1 Specification] and SVGLength is not designed to handle that.
With this change, we now pretend that "order" is a string, which side
steps this issue.
[SVG 1.1 Specification]: https://www.w3.org/TR/SVG11/single-page.html#filters-feConvolveMatrixElementOrderAttribute
Closes: #189
> removeDefaultAttributeValue: Special-case order attribute

- scour/scour.py
- testscour.py
- unittests/shorten-ids-stable-output.svg
This patch enables shortenIDs to remap IDs currently in use.  This is
very helpful to ensure that scour does not change been "optimal" and
"suboptimal" choices for IDs as observed in GH#186.
Closes: #186
> Enable shortenIDs to recycle existing IDs

- scour/scour.py
- testscour.py
- unittests/group-sibling-merge.svg
In some cases, gnuplot generates a very suboptimal SVG content of the
following pattern:
<g color="black" fill="none" stroke="currentColor">
<path d="m82.5 323.3v-4.1" stroke="#000"/>
</g>
<g color="black" fill="none" stroke="currentColor">
<path d="m116.4 323.3v-4.1" stroke="#000"/>
</g>
... repeated 10+ more times here ...
<g color="black" fill="none" stroke="currentColor">
<path d="m65.4 72.8v250.5h420v-250.5h-420z" stroke="#000"/>
</g>
A more optimal pattern would be:
<g color="black" fill="none" stroke="#000">
<path d="m82.5 323.3v-4.1"/>
<path d="m116.4 323.3v-4.1"/>
... 10+ more paths here ...
<path d="m65.4 72.8v250.5h420v-250.5h-420z"/>
</g>
This patch enables that optimization by handling the merging of two
sibling <g> entries that have identical attributes.  In the above …
> Merge sibling <g> nodes with identical attributes
