scour-project/scour

- scour/__init__.py
- scour/scour.py
- scour/svg_regex.py
- scour/svg_transform.py
- setup.py
Ran python-modernizer, this fixed most of the Python 3
incompatibilities.
Had to manually rework the iteration in svg_regex and svg_transform;
.next doesn't exist in Python 3. Wrapped the builtin next function in a
partial for equivalent functionality.
> Python 3 Updates

- scour/scour.py
This PR allows Scour to remove unused XML namespace declarations.
> Remove unused XML namespace declarations

- README.md
- scour/scour.py
• Initial support for Sketch (#35)
• Typos in README.md (#36)
> Sketch support

- .travis.yml
- tox.ini
Here's a very basic implementation to use Travis CI, since it is time to tackle #31 to prevent glitches like #51 in future.
In principle it already works as tested in [my fork](https://github.com/Ede123/scour). So far it installs Scour, checks the installation by calling `scour --version` and runs `testscour.py`.
For example the initial build of master [failed](https://travis-ci.org/Ede123/scour/jobs/120202729), but my dummy pull request made it [pass](https://travis-ci.org/Ede123/scour/builds/120206007).
This is not (yet) meant to be a final PR, but to start discussion on what should be implemented (I'm just getting started with CI myself and am learning as I go), so let me know what you think.
On the other hand it seems to me even this basic functionality is already a big help and we …
> Basic implementation for Travis CI

- scour/scour.py
- testscour.py
"No" is the default value anyway...
(Also avoids #55)
> Only include "standalone" attribute if it was explicitly set to "yes"

- scour/scour.py
- testscour.py
- unittests/unreferenced-defs.svg
> Don't remove unreferenced defs if `--keep-unreferenced-defs` is specified

- scour/scour.py
- testscour.py
- unittests/ids.svg
especially useful for unittests...
> Allow elements to be found via Document.getElementById()

- scour/scour.py
- testscour.py
- unittests/gradient-default-attrs.svg
This makes it much easier to extend the list and should increase code clarity.
> Improve code for removal of default attributes

- scour/scour.py
> Fix/update list of SVG presentation attributes

- scour/scour.py
> Fix removal rules for the `overflow` attribute

- scour/scour.py
Fixes #106.
It looks like the existing logic already takes care of empty declarations, extra spaces etc.
> sort style declarations

- scour/scour.py
- testscour.py
- unittests/path-bez-optimize.svg
Fix conversion of cubic Bézier "curveto" commands into "shorthand/smooth curveto" commands.
> Curveto optimization fix

- scour/scour.py
- testscour.py
- unittests/stroke-none.svg
Fix some incorrect style removals due to ignorance of inheritance (fixes #22)
> Property inheritance

- testscour.py
- unittests/ids-protect.svg
- unittests/minimal.svg
- unittests/xml-space.svg
I'll add some unittests to this branch aiming at increased coverage
> Add some unittests

- scour/scour.py
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
> Python 3.6 invalid escape sequence deprecation fixes

- scour/scour.py
- testscour.py
Here a two commits that fixes the newly reported flake8 failures noted in #165
> Flake8 fixes

- scour/scour.py
> Gracefully handle unreferenced gradients with --keep-unreferenced-defs

- scour/scour.py
Two small commits that remove some redundant code.
> Minor cleanup - remove some redundant code

- scour/scour.py
- testscour.py
- unittests/collapse-gradients-preserve-xlink-href.svg
> Preserve xhref:href attr when collapsing referenced gradients

- scour/scour.py
> convertColors: Fix bug in computation in how many bytes are saved

- scour/scour.py
- test_scour.py
Some commits to reduce the overhead in outputting the SVG again (most of it is in `serializeXML` and below)
> Perf optimized serialization

- scour/scour.py
- scour/stats.py
Largest bit is removal of global variables but also includes a few minor other things.
> Refactor bits
